volumes:
  n8n_data:

networks:
  n8n-network:
    name: n8n-network

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    networks:
      - n8n-network
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n.sunshine.me
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.sunshine.me
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_DIAGNOSTICS_ENABLED=false
    volumes:
      - n8n_data:/home/node/.n8n

  cloudflared:
    container_name: n8n-cloudflared
    image: cloudflare/cloudflared:latest
    networks:
      - n8n-network
    environment:
      TZ: Europe/Berlin
    command:
      [
        "tunnel",
        "--no-autoupdate",
        "run",
        "--token",
        "${CLOUDFLARED_TOKEN}"
      ]
    restart: unless-stopped
